// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  CodecTypes as PgVectorTypes,
  Vector,
} from '@prisma/orm-extension-pgvector/codec-types';
import type { QueryOperationTypes as PgVectorQueryOperationTypes } from '@prisma/orm-extension-pgvector/operation-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'7ff1d3cf141e9dd0ed8a1f2c0880cca598ee9a6edfc0907442f2138ef224a7eb'>;
export type ExecutionHash =
  ExecutionHashBase<'e4e69d8dd7aa95f034f9c67aee213f56c94a2a9c3815e6ca64c3370db618e0cf'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes & PgVectorTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  PgVectorQueryOperationTypes<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly conversationId: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly activityId: CodecTypes['pg/text@1']['output'];
      readonly timestamp: CodecTypes['pg/text@1']['output'];
      readonly blob: CodecTypes['pg/jsonb@1']['output'];
    };
    readonly EventSession: {
      readonly conversationId: CodecTypes['pg/text@1']['output'];
      readonly documentId: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly pendingUrls: CodecTypes['pg/jsonb@1']['output'];
      readonly activeSource: CodecTypes['pg/text@1']['output'] | null;
      readonly activeFileName: CodecTypes['pg/text@1']['output'] | null;
      readonly startedBy: CodecTypes['pg/text@1']['output'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Feedback: {
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly replyToId: CodecTypes['pg/text@1']['output'];
      readonly reaction: CodecTypes['pg/text@1']['output'];
      readonly feedback: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RagChunk: {
      readonly documentId: CodecTypes['pg/text@1']['output'];
      readonly chunkId: CodecTypes['pg/text@1']['output'];
      readonly sheet: CodecTypes['pg/text@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
      readonly rowJson: CodecTypes['pg/jsonb@1']['output'];
      readonly embedding: Vector<384>;
      readonly dims: CodecTypes['pg/int4@1']['output'];
    };
    readonly RagDocument: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly sourceType: CodecTypes['pg/text@1']['output'];
      readonly sourceUri: CodecTypes['pg/text@1']['output'];
      readonly fileName: CodecTypes['pg/text@1']['output'] | null;
      readonly contentHash: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RagMeta: {
      readonly documentId: CodecTypes['pg/text@1']['output'];
      readonly fingerprint: CodecTypes['pg/text@1']['output'];
      readonly provider: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly dims: CodecTypes['pg/int4@1']['output'];
      readonly chunkCount: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly RagSharepointSource: {
      readonly documentId: CodecTypes['pg/text@1']['output'];
      readonly driveId: CodecTypes['pg/text@1']['output'] | null;
      readonly itemId: CodecTypes['pg/text@1']['output'] | null;
      readonly siteId: CodecTypes['pg/text@1']['output'] | null;
      readonly webUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly subscriptionId: CodecTypes['pg/text@1']['output'] | null;
      readonly subscriptionExpiresAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly deltaLink: CodecTypes['pg/text@1']['output'] | null;
      readonly etag: CodecTypes['pg/text@1']['output'] | null;
      readonly lastModifiedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly lastDeltaSyncAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly conversationId: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly activityId: CodecTypes['pg/text@1']['input'];
      readonly timestamp: CodecTypes['pg/text@1']['input'];
      readonly blob: CodecTypes['pg/jsonb@1']['input'];
    };
    readonly EventSession: {
      readonly conversationId: CodecTypes['pg/text@1']['input'];
      readonly documentId: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly pendingUrls: CodecTypes['pg/jsonb@1']['input'];
      readonly activeSource: CodecTypes['pg/text@1']['input'] | null;
      readonly activeFileName: CodecTypes['pg/text@1']['input'] | null;
      readonly startedBy: CodecTypes['pg/text@1']['input'] | null;
      readonly startedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Feedback: {
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly replyToId: CodecTypes['pg/text@1']['input'];
      readonly reaction: CodecTypes['pg/text@1']['input'];
      readonly feedback: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RagChunk: {
      readonly documentId: CodecTypes['pg/text@1']['input'];
      readonly chunkId: CodecTypes['pg/text@1']['input'];
      readonly sheet: CodecTypes['pg/text@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
      readonly rowJson: CodecTypes['pg/jsonb@1']['input'];
      readonly embedding: CodecTypes['pg/vector@1']['input'];
      readonly dims: CodecTypes['pg/int4@1']['input'];
    };
    readonly RagDocument: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly sourceType: CodecTypes['pg/text@1']['input'];
      readonly sourceUri: CodecTypes['pg/text@1']['input'];
      readonly fileName: CodecTypes['pg/text@1']['input'] | null;
      readonly contentHash: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RagMeta: {
      readonly documentId: CodecTypes['pg/text@1']['input'];
      readonly fingerprint: CodecTypes['pg/text@1']['input'];
      readonly provider: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly dims: CodecTypes['pg/int4@1']['input'];
      readonly chunkCount: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly RagSharepointSource: {
      readonly documentId: CodecTypes['pg/text@1']['input'];
      readonly driveId: CodecTypes['pg/text@1']['input'] | null;
      readonly itemId: CodecTypes['pg/text@1']['input'] | null;
      readonly siteId: CodecTypes['pg/text@1']['input'] | null;
      readonly webUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly subscriptionId: CodecTypes['pg/text@1']['input'] | null;
      readonly subscriptionExpiresAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly deltaLink: CodecTypes['pg/text@1']['input'] | null;
      readonly etag: CodecTypes['pg/text@1']['input'] | null;
      readonly lastModifiedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly lastDeltaSyncAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly conversations: {
      readonly activity_id: CodecTypes['pg/text@1']['output'];
      readonly blob: CodecTypes['pg/jsonb@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly conversation_id: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly timestamp: CodecTypes['pg/text@1']['output'];
    };
    readonly event_sessions: {
      readonly active_file_name: CodecTypes['pg/text@1']['output'] | null;
      readonly active_source: CodecTypes['pg/text@1']['output'] | null;
      readonly conversation_id: CodecTypes['pg/text@1']['output'];
      readonly document_id: CodecTypes['pg/text@1']['output'] | null;
      readonly pending_urls: CodecTypes['pg/jsonb@1']['output'];
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly started_by: CodecTypes['pg/text@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly feedback: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly feedback: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int8@1']['output'];
      readonly reaction: CodecTypes['pg/text@1']['output'];
      readonly reply_to_id: CodecTypes['pg/text@1']['output'];
    };
    readonly rag_chunks: {
      readonly chunk_id: CodecTypes['pg/text@1']['output'];
      readonly dims: CodecTypes['pg/int4@1']['output'];
      readonly document_id: CodecTypes['pg/text@1']['output'];
      readonly embedding: Vector<384>;
      readonly row_json: CodecTypes['pg/jsonb@1']['output'];
      readonly sheet: CodecTypes['pg/text@1']['output'];
      readonly text: CodecTypes['pg/text@1']['output'];
    };
    readonly rag_documents: {
      readonly content_hash: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly file_name: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly source_type: CodecTypes['pg/text@1']['output'];
      readonly source_uri: CodecTypes['pg/text@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly rag_meta: {
      readonly chunk_count: CodecTypes['pg/int4@1']['output'];
      readonly dims: CodecTypes['pg/int4@1']['output'];
      readonly document_id: CodecTypes['pg/text@1']['output'];
      readonly fingerprint: CodecTypes['pg/text@1']['output'];
      readonly model: CodecTypes['pg/text@1']['output'];
      readonly provider: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly rag_sharepoint_sources: {
      readonly delta_link: CodecTypes['pg/text@1']['output'] | null;
      readonly document_id: CodecTypes['pg/text@1']['output'];
      readonly drive_id: CodecTypes['pg/text@1']['output'] | null;
      readonly etag: CodecTypes['pg/text@1']['output'] | null;
      readonly item_id: CodecTypes['pg/text@1']['output'] | null;
      readonly last_delta_sync_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly last_modified_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly site_id: CodecTypes['pg/text@1']['output'] | null;
      readonly subscription_expires_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly subscription_id: CodecTypes['pg/text@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly web_url: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly conversations: {
      readonly activity_id: CodecTypes['pg/text@1']['input'];
      readonly blob: CodecTypes['pg/jsonb@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly conversation_id: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly timestamp: CodecTypes['pg/text@1']['input'];
    };
    readonly event_sessions: {
      readonly active_file_name: CodecTypes['pg/text@1']['input'] | null;
      readonly active_source: CodecTypes['pg/text@1']['input'] | null;
      readonly conversation_id: CodecTypes['pg/text@1']['input'];
      readonly document_id: CodecTypes['pg/text@1']['input'] | null;
      readonly pending_urls: CodecTypes['pg/jsonb@1']['input'];
      readonly started_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly started_by: CodecTypes['pg/text@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly feedback: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly feedback: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int8@1']['input'];
      readonly reaction: CodecTypes['pg/text@1']['input'];
      readonly reply_to_id: CodecTypes['pg/text@1']['input'];
    };
    readonly rag_chunks: {
      readonly chunk_id: CodecTypes['pg/text@1']['input'];
      readonly dims: CodecTypes['pg/int4@1']['input'];
      readonly document_id: CodecTypes['pg/text@1']['input'];
      readonly embedding: CodecTypes['pg/vector@1']['input'];
      readonly row_json: CodecTypes['pg/jsonb@1']['input'];
      readonly sheet: CodecTypes['pg/text@1']['input'];
      readonly text: CodecTypes['pg/text@1']['input'];
    };
    readonly rag_documents: {
      readonly content_hash: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly file_name: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly source_type: CodecTypes['pg/text@1']['input'];
      readonly source_uri: CodecTypes['pg/text@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly rag_meta: {
      readonly chunk_count: CodecTypes['pg/int4@1']['input'];
      readonly dims: CodecTypes['pg/int4@1']['input'];
      readonly document_id: CodecTypes['pg/text@1']['input'];
      readonly fingerprint: CodecTypes['pg/text@1']['input'];
      readonly model: CodecTypes['pg/text@1']['input'];
      readonly provider: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly rag_sharepoint_sources: {
      readonly delta_link: CodecTypes['pg/text@1']['input'] | null;
      readonly document_id: CodecTypes['pg/text@1']['input'];
      readonly drive_id: CodecTypes['pg/text@1']['input'] | null;
      readonly etag: CodecTypes['pg/text@1']['input'] | null;
      readonly item_id: CodecTypes['pg/text@1']['input'] | null;
      readonly last_delta_sync_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly last_modified_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly site_id: CodecTypes['pg/text@1']['input'] | null;
      readonly subscription_expires_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly subscription_id: CodecTypes['pg/text@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly web_url: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Conversation = {
    id: CodecTypes['pg/int8@1']['output'];
    conversationId: CodecTypes['pg/text@1']['output'];
    role: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    content: CodecTypes['pg/text@1']['output'];
    activityId: CodecTypes['pg/text@1']['output'];
    timestamp: CodecTypes['pg/text@1']['output'];
    blob: CodecTypes['pg/jsonb@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Feedback = {
    id: CodecTypes['pg/int8@1']['output'];
    replyToId: CodecTypes['pg/text@1']['output'];
    reaction: CodecTypes['pg/text@1']['output'];
    feedback: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_RagDocument = {
    id: CodecTypes['pg/text@1']['output'];
    sourceType: CodecTypes['pg/text@1']['output'];
    sourceUri: CodecTypes['pg/text@1']['output'];
    fileName: CodecTypes['pg/text@1']['output'] | null;
    contentHash: CodecTypes['pg/text@1']['output'] | null;
    status: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    chunks: public_RagChunk[];
    meta: public_RagMeta | null;
    sessions: public_EventSession[];
    sharepoint: public_RagSharepointSource | null;
    readonly [RelationKeys]?: 'chunks' | 'meta' | 'sessions' | 'sharepoint';
  };
  export type public_RagSharepointSource = {
    documentId: CodecTypes['pg/text@1']['output'];
    driveId: CodecTypes['pg/text@1']['output'] | null;
    itemId: CodecTypes['pg/text@1']['output'] | null;
    siteId: CodecTypes['pg/text@1']['output'] | null;
    webUrl: CodecTypes['pg/text@1']['output'] | null;
    subscriptionId: CodecTypes['pg/text@1']['output'] | null;
    subscriptionExpiresAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    deltaLink: CodecTypes['pg/text@1']['output'] | null;
    etag: CodecTypes['pg/text@1']['output'] | null;
    lastModifiedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    lastDeltaSyncAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    document: public_RagDocument;
    readonly [RelationKeys]?: 'document';
  };
  export type public_EventSession = {
    conversationId: CodecTypes['pg/text@1']['output'];
    documentId: CodecTypes['pg/text@1']['output'] | null;
    status: CodecTypes['pg/text@1']['output'];
    pendingUrls: CodecTypes['pg/jsonb@1']['output'];
    activeSource: CodecTypes['pg/text@1']['output'] | null;
    activeFileName: CodecTypes['pg/text@1']['output'] | null;
    startedBy: CodecTypes['pg/text@1']['output'] | null;
    startedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    document: public_RagDocument | null;
    readonly [RelationKeys]?: 'document';
  };
  export type public_RagMeta = {
    documentId: CodecTypes['pg/text@1']['output'];
    fingerprint: CodecTypes['pg/text@1']['output'];
    provider: CodecTypes['pg/text@1']['output'];
    model: CodecTypes['pg/text@1']['output'];
    dims: CodecTypes['pg/int4@1']['output'];
    chunkCount: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    document: public_RagDocument;
    readonly [RelationKeys]?: 'document';
  };
  export type public_RagChunk = {
    documentId: CodecTypes['pg/text@1']['output'];
    chunkId: CodecTypes['pg/text@1']['output'];
    sheet: CodecTypes['pg/text@1']['output'];
    text: CodecTypes['pg/text@1']['output'];
    rowJson: CodecTypes['pg/jsonb@1']['output'];
    embedding: Vector<384>;
    dims: CodecTypes['pg/int4@1']['output'];
    document: public_RagDocument;
    readonly [RelationKeys]?: 'document';
  };
}

export declare const models: {
  public: {
    Conversation: Models.public_Conversation;
    Feedback: Models.public_Feedback;
    RagDocument: Models.public_RagDocument;
    RagSharepointSource: Models.public_RagSharepointSource;
    EventSession: Models.public_EventSession;
    RagMeta: Models.public_RagMeta;
    RagChunk: Models.public_RagChunk;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly conversations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly conversation_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly activity_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly timestamp: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly blob: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_conversations_conversation_id';
                  readonly columns: readonly ['conversation_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'idx_conversations_timestamp';
                  readonly columns: readonly ['conversation_id', 'timestamp'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly event_sessions: {
              columns: {
                readonly conversation_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly document_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pending_urls: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/jsonb@1', '[]'>;
                  };
                };
                readonly active_source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly active_file_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly started_by: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly started_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['conversation_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_event_sessions_document_id';
                  readonly columns: readonly ['document_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'idx_event_sessions_status';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event_sessions';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly feedback: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly reply_to_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reaction: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly feedback: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_feedback_reply_to_id';
                  readonly columns: readonly ['reply_to_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly rag_chunks: {
              columns: {
                readonly document_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly chunk_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sheet: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly row_json: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly embedding: {
                  readonly nativeType: 'vector';
                  readonly codecId: 'pg/vector@1';
                  readonly nullable: false;
                  readonly typeRef: 'Embedding384';
                };
                readonly dims: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['document_id', 'chunk_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_rag_chunks_sheet';
                  readonly columns: readonly ['document_id', 'sheet'];
                  readonly unique: false;
                },
                {
                  readonly name: 'rag_chunks_document_id_idx_d3d0944e';
                  readonly prefix: 'rag_chunks_document_id_idx';
                  readonly columns: readonly ['document_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_chunks';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly rag_documents: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly source_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly source_uri: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly file_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly content_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pending'>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_rag_documents_status';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'idx_rag_documents_content_hash';
                  readonly columns: readonly ['content_hash'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly rag_meta: {
              columns: {
                readonly document_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly fingerprint: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly provider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly model: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly dims: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly chunk_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['document_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_meta';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly rag_sharepoint_sources: {
              columns: {
                readonly document_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly drive_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly item_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly site_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly web_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly subscription_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly subscription_expires_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly delta_link: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly etag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly last_modified_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly last_delta_sync_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['document_id'] };
              uniques: readonly [
                {
                  readonly columns: readonly ['drive_id', 'item_id'];
                  readonly name: 'uq_rag_sharepoint_drive_item';
                },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_sharepoint_sources';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'rag_documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly types: {
      readonly Embedding384: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/vector@1';
        readonly nativeType: 'vector';
        readonly typeParams: { readonly length: 384 };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly conversations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Conversation';
    };
    readonly feedback: { readonly namespace: 'public' & NamespaceId; readonly model: 'Feedback' };
    readonly rag_documents: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RagDocument';
    };
    readonly rag_sharepoint_sources: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RagSharepointSource';
    };
    readonly event_sessions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'EventSession';
    };
    readonly rag_meta: { readonly namespace: 'public' & NamespaceId; readonly model: 'RagMeta' };
    readonly rag_chunks: { readonly namespace: 'public' & NamespaceId; readonly model: 'RagChunk' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Conversation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly conversationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activityId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timestamp: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly blob: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'conversations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly conversationId: { readonly column: 'conversation_id' };
                readonly role: { readonly column: 'role' };
                readonly name: { readonly column: 'name' };
                readonly content: { readonly column: 'content' };
                readonly activityId: { readonly column: 'activity_id' };
                readonly timestamp: { readonly column: 'timestamp' };
                readonly blob: { readonly column: 'blob' };
              };
            };
          };
          readonly EventSession: {
            readonly fields: {
              readonly conversationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly documentId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pendingUrls: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly activeSource: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly activeFileName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedBy: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagDocument';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'event_sessions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly conversationId: { readonly column: 'conversation_id' };
                readonly documentId: { readonly column: 'document_id' };
                readonly status: { readonly column: 'status' };
                readonly pendingUrls: { readonly column: 'pending_urls' };
                readonly activeSource: { readonly column: 'active_source' };
                readonly activeFileName: { readonly column: 'active_file_name' };
                readonly startedBy: { readonly column: 'started_by' };
                readonly startedAt: { readonly column: 'started_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Feedback: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly replyToId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reaction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly feedback: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'feedback';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly replyToId: { readonly column: 'reply_to_id' };
                readonly reaction: { readonly column: 'reaction' };
                readonly feedback: { readonly column: 'feedback' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly RagChunk: {
            readonly fields: {
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly chunkId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sheet: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rowJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly embedding: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/vector@1' };
              };
              readonly dims: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagDocument';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rag_chunks';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly documentId: { readonly column: 'document_id' };
                readonly chunkId: { readonly column: 'chunk_id' };
                readonly sheet: { readonly column: 'sheet' };
                readonly text: { readonly column: 'text' };
                readonly rowJson: { readonly column: 'row_json' };
                readonly embedding: { readonly column: 'embedding' };
                readonly dims: { readonly column: 'dims' };
              };
            };
          };
          readonly RagDocument: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sourceType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sourceUri: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fileName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contentHash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly chunks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagChunk';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
              readonly meta: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagMeta';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'EventSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
              readonly sharepoint: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagSharepointSource';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rag_documents';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly sourceType: { readonly column: 'source_type' };
                readonly sourceUri: { readonly column: 'source_uri' };
                readonly fileName: { readonly column: 'file_name' };
                readonly contentHash: { readonly column: 'content_hash' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly RagMeta: {
            readonly fields: {
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fingerprint: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly model: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dims: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly chunkCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagDocument';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rag_meta';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly documentId: { readonly column: 'document_id' };
                readonly fingerprint: { readonly column: 'fingerprint' };
                readonly provider: { readonly column: 'provider' };
                readonly model: { readonly column: 'model' };
                readonly dims: { readonly column: 'dims' };
                readonly chunkCount: { readonly column: 'chunk_count' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly RagSharepointSource: {
            readonly fields: {
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly driveId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly itemId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly siteId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly webUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subscriptionId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subscriptionExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deltaLink: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly etag: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastModifiedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly lastDeltaSyncAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'RagDocument';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'rag_sharepoint_sources';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly documentId: { readonly column: 'document_id' };
                readonly driveId: { readonly column: 'drive_id' };
                readonly itemId: { readonly column: 'item_id' };
                readonly siteId: { readonly column: 'site_id' };
                readonly webUrl: { readonly column: 'web_url' };
                readonly subscriptionId: { readonly column: 'subscription_id' };
                readonly subscriptionExpiresAt: { readonly column: 'subscription_expires_at' };
                readonly deltaLink: { readonly column: 'delta_link' };
                readonly etag: { readonly column: 'etag' };
                readonly lastModifiedAt: { readonly column: 'last_modified_at' };
                readonly lastDeltaSyncAt: { readonly column: 'last_delta_sync_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly 'pgvector.cosine': true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly pgvector: {
      readonly capabilities: { readonly postgres: { readonly 'pgvector.cosine': true } };
      readonly familyId: 'sql';
      readonly id: 'pgvector';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PgVectorTypes';
            readonly named: 'CodecTypes';
            readonly package: '@internal/extension-pgvector/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'Vector';
              readonly named: 'Vector';
              readonly package: '@internal/extension-pgvector/codec-types';
            },
          ];
        };
        readonly operationTypes: {
          readonly import: {
            readonly alias: 'PgVectorOperationTypes';
            readonly named: 'OperationTypes';
            readonly package: '@internal/extension-pgvector/operation-types';
          };
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'PgVectorQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@internal/extension-pgvector/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'vector';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/vector@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'rag_documents';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
